### ISSUE TITLE
 How to get the predictions from the XLNet

### ISSUE THREAD

**Issue by strivedi02** [aditya-malte/Colab-XLNet-FineTuning#3]
I have trained the model by doing some modifications in the yelp5processor. The model has been trained. Now I want to get the predictions of the test sentences for which I don't have the actual Y, I just want to retrieve the predicted Y values from the trained model.
If someone could give an example in the colab file that would be a lot helpful.
Any Help will be appreciated.

**Comment by aditya-malte** [comment]
Hello, I think you should take a look at the "predict" function. Try using the below command:

python run_classifier.py \
  --use_tpu=True \
  --use_colab_tpu=True \
  --do_train=False \
  --do_predict=True \
  --task_name="+TASK.lower()+" \
  --data_dir=./"+TASK_DATA_DIR+" \
  --output_dir="+OUTPUT_DIR+" \
  --model_dir="+OUTPUT_DIR+" \
  --uncased=False \
  --tpu_address="+TPU_ADDRESS+"  \
  --spiece_model_file=./spiece.model \
  --model_config_path="+MODEL_DIR+"/xlnet_config.json \
  --init_checkpoint="+MODEL_DIR+"/xlnet_model.ckpt \
  --max_seq_length="+str(MAX_SEQ_LENGTH)+" \
  --train_batch_size="+str(TRAIN_BATCH_SIZE)+" \
  --num_hosts=1 \
  --num_core_per_host=8 \

**Comment by pluieciel** [comment]
You might also need these lines:
--predict_dir=predict_out \\
--predict_ckpt="+OUTPUT_DIR+"/model.ckpt-2800 \\
--overwrite_data=True \

And for me, the order of my input seems shuffled, so i modified 'guid' and add a line in run_classifier:
```
  if FLAGS.do_predict:
    eval_file_base = "{}.len-{}.{}.predict.tf_record".format(
        spm_basename, FLAGS.max_seq_length, FLAGS.eval_split)
    eval_file = os.path.join(FLAGS.output_dir, eval_file_base)
    **eval_examples=sorted(eval_examples,key=lambda x:x.guid)**
```

**Comment by aditya-malte** [comment]
Thanks for pointing that out @pluieciel
