### ISSUE TITLE
issue of Dir when eval

### ISSUE THREAD

**Issue by pluieciel** [aditya-malte/Colab-XLNet-FineTuning#5]
Hi, it's me again. Thanks for your notebook!

I just find that the init Weight should be in a different directory from the saved ckpt. Or there will be error when doing eval.
in the notebook, you put init weight in MODEL_DIR
I think in training:
  --output_dir="+OUTPUT_DIR+" \
  --model_dir="+MODEL_DIR+" \
should be:
  --output_dir="+OUTPUT_DIR+" \
  --model_dir="+OUTPUT_DIR+"
to separate init weight from save ckpt.

**Comment by aditya-malte** [comment]
Hello @pluieciel ,
I have kept the model_dir separate from the output_dir, to avoid confusion as to the pretrained weights and finetuned weights during the training phase (as was discussed with @kimiyoung on the original xlnet repo). During the eval phase we are simply loading the model weights from the fine-tuned checkpoint and no generation of additional checkpoints is done.
Furthermore, the code is working perfectly fine as per my tests, both during fine-tuning and eval. Please let me know if you are facing any issues/errors with the repo.
Thank you

**Comment by pluieciel** [comment]
Hi @aditya-malte 
in your version, the pretrained ckpt saved in MODEL_DIR.
in training, the ckpt saved in --model_dir="+MODEL_DIR+", which is the same dir of pretrain.
then, in eval, the code rise a error, since `global_step = int(cur_filename.split("-")[-1])` and there is no '-' in pretrain ckpt.

**Comment by aditya-malte** [comment]
I'm sorry but there seems to be no error. In fact I ran the code successfully and even get a score of around 0.92 on the IMDB task.
Furthermore, during eval phase, the model graph is loaded from the model directory while the checkpoint is loaded from the output directory.
Thank you

**Comment by pluieciel** [comment]
Not a big problem, just that in your notebook,
train_command: --model_dir="+MODEL_DIR+"
eval_command: --model_dir="+OUTPUT_DIR+"
I think it is a little typo. ckpt dir should be the same. or I need to copy all ckpt from MODEL_DIR into OUTPUT_DIR with 'gsutil cp'.

And thanks again for the guide to use TPU, it really saves me lots of time!

**Comment by aditya-malte** [comment]
Hello,
I don't know what are you running exactly, but the code should run end-to-end without interruption, please share the error message if you face it.

Welcome :). The TPUEstimator api is a real struggle and I feel happy that this notebook is helping people.

**Comment by aditya-malte** [comment]
As always, do share it if you find it useful xD
